blank_issues_enabled: true
issue_templates:
  - name: "Bug Report"
    description: "Create a report to help us improve"
    title: "[BUG] "
    labels: ["bug"]
    body: "./ISSUE_TEMPLATE/bug_report.md"
  - name: "Feature Request"
    description: "Suggest an idea for this project"
    title: "[FEATURE] "
    labels: ["enhancement"]
    body: "./ISSUE_TEMPLATE/feature_request.md"
  - name: "Documentation"
    description: "Suggest updates or additions to the documentation"
    title: "[DOCS] "
    labels: ["documentation"]
    body: "./ISSUE_TEMPLATE/documentation.md"